name: MaskFS Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux32:
    name: Build Linux x32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install 32-bit dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386

      - name: Install Rust toolchain
        run: |
          rustup install nightly
          rustup default nightly
          rustup target add i686-unknown-linux-gnu

      - name: Build
        run: cargo build --release --target i686-unknown-linux-gnu

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/i686-unknown-linux-gnu/release/libgm_maskfs.so
          tag_name: ${{ github.ref }}
          name: gmsv_gm_maskfs_linux.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux64:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: |
          rustup install nightly
          rustup default nightly
          rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/libgm_maskfs.so
          tag_name: ${{ github.ref }}
          name: gmsv_gm_maskfs_linux64.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win32:
    name: Build Windows x32
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: |
          rustup install nightly
          rustup default nightly
          rustup target add i686-pc-windows-msvc

      - name: Build
        run: cargo build --release --target i686-pc-windows-msvc

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/i686-pc-windows-msvc/release/gm_maskfs.dll
          tag_name: ${{ github.ref }}
          name: gmsv_gm_maskfs_win32.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win64:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: |
          rustup install nightly
          rustup default nightly
          rustup target add x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-pc-windows-msvc/release/gm_maskfs.dll
          tag_name: ${{ github.ref }}
          name: gmsv_gm_maskfs_win64.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
